apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh", "-c", "echo Hello from app && sleep 3600"]
  - name: sidecar
    image: busybox
    command: ["sh", "-c", "echo Hello from sidecar && sleep 3600"]
