apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 20Gi
  accessModes: [ ReadWriteMany ]
  nfs:
    server: 10.0.0.50
    path: /exports/teamdata
  persistentVolumeReclaimPolicy: Retain
