apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-lb
spec:
  selector:
    app: nginx-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc-lb
spec:
  selector:
    app: api-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: web-svc-lb
spec:
  selector:
    app: web-app
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: shop-svc-lb
spec:
  selector:
    app: shop-app
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: secure-svc-lb
spec:
  selector:
    app: secure-app
  ports:
  - protocol: TCP
    port: 8443
    targetPort: 443
  type: LoadBalancer