apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-app
  template:
    metadata:
      labels:
        app: secure-app
    spec:
      containers:
      - name: secure-container
        image: secure-app:latest
        ports:
        - containerPort: 443
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: secure-svc
spec:
  selector:
    app: secure-app
  ports:
  - protocol: TCP
    port: 443
    targetPort: 443
  type: NodePort