apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels: { app: web }
  template:
    metadata:
      labels: { app: web }
    spec:
      containers:
      - name: web
        image: web-app:latest
        ports:
        - containerPort: 8080
        startupProbe:
          httpGet: { path: /healthz/startup, port: 8080 }
          failureThreshold: 30         # up to 30 * 1s = 30s to start
          periodSeconds: 1
        readinessProbe:
          httpGet: { path: /healthz/ready, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 2          # 2 consecutive fails => NotReady
        livenessProbe:
          httpGet: { path: /healthz/live, port: 8080 }
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 3          # 3 consecutive fails => restart
