apiVersion: v1
kind: Pod
metadata:
  name: demo
spec:
  containers:
  - name: app
    image: busybox
    command: ["sh","-c","echo $APP_ENV && sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config
    - secretRef:
        name: db-secret
