
apiVersion: v1
kind: Secret
metadata:
  name: pg-secret
type: Opaque
data:
  password: bXlwYXNzd29yZDEyMw==   # "mypassword123" (base64 encoded)
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
spec:
  clusterIP: None            # headless
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db-svc        # ties to headless svc
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: postgres
        image: postgres:16
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pg-secret
              key: password
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
      storageClassName: standard   # or your dynamic SC
